version: '2'
services:
    postgres:
        image: postgres:9-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=swme
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        container_name: postgres
        