version: '2'
services:
    postgres:
        image: postgres:9-alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=swme
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        container_name: postgres

    tomcat:
        image: tomcat:8-alpine
        ports:
            - "8080:8080"
        environment:
            - JAVA_OPTS="-Dspring.profiles.active=prod"
        volumes:
            - ./webapps:/usr/local/tomcat/webapps
        links:
            - postgres:postgres
        container_name: tomcat
    
