-- MSc suffix
-- BSc suffix
-- BA suffix
-- Bakkalaureus suffix
-- Dr. prefix
-- Phd suffix
-- Dipl. -Ing suffix


-- create new title table and its pk sequence
CREATE SEQUENCE SQ_TITLE_PK START 1;

CREATE TABLE TITLE(
    TITLE_PK INTEGER DEFAULT nextval('SQ_TITLE_PK'),
    NAME VARCHAR(15) NOT NULL,
    IS_PRECEDING BOOLEAN NOT NULL,
    CONSTRAINT C_TITLE_PK PRIMARY KEY(TITLE_PK)
);

-- insert new titles
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'MSc', 'false');
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'BSc', 'false');
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'BA', 'false');
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'Bachelor', 'false');
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'Dr.', 'true');
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'PhD', 'false');
INSERT INTO TITLE VALUES (nextval('SQ_TITLE_PK'),'Dipl. -Ing', 'false');


-- add foreign key to person table
ALTER TABLE PERSON ADD COLUMN TITLE_ID INTEGER;
ALTER TABLE PERSON ADD CONSTRAINT FK_TITLE FOREIGN KEY (TITLE_ID) REFERENCES TITLE(TITLE_PK);

-- change the not null on existing title column
ALTER TABLE PERSON ALTER COLUMN TITLE DROP NOT NULL;

UPDATE PERSON
SET TITLE_ID = (SELECT TITLE_PK FROM TITLE WHERE NAME = 'MSc')
WHERE TITLE LIKE 'MSc%';

UPDATE PERSON
SET TITLE_ID = (SELECT TITLE_PK FROM TITLE WHERE NAME = 'BSc')
WHERE TITLE LIKE 'BSc%';

UPDATE PERSON
SET TITLE_ID = (SELECT TITLE_PK FROM TITLE WHERE NAME = 'Dr.')
WHERE TITLE LIKE 'Dr.%' OR TITLE LIKE 'Doktor%';

UPDATE PERSON
SET TITLE_ID = (SELECT TITLE_PK FROM TITLE WHERE NAME = 'Dipl. -Ing')
WHERE TITLE LIKE '%Ing%' OR TITLE LIKE  'DI%';

UPDATE PERSON
SET TITLE_ID = (SELECT TITLE_PK FROM TITLE WHERE NAME = 'PhD')
WHERE TITLE LIKE 'Phd%' OR TITLE LIKE 'PhD%';

UPDATE PERSON
SET TITLE_ID = (SELECT TITLE_PK FROM TITLE WHERE NAME = 'Bachelor')
WHERE TITLE LIKE 'Bakk%' OR TITLE LIKE 'Bachelor';




