-- create new COUNTRY table and its pk sequence
CREATE SEQUENCE SQ_COUNTRY_PK START 1;

CREATE TABLE COUNTRY(
  COUNTRY_PK INTEGER DEFAULT nextval('SQ_COUNTRY_PK'),
  CODE VARCHAR(2) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  CONSTRAINT C_COUNTRY_PK PRIMARY KEY(COUNTRY_PK)
);

-- add a coutry id column to addresses
-- add foreign key to address table
ALTER TABLE ADDRESS ADD COLUMN COUNTRY_ID INTEGER;
ALTER TABLE ADDRESS ADD CONSTRAINT FK_COUNTRY FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(COUNTRY_PK);

-- insert countries to db
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AF', 'Afghanistan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AL', 'Albania');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DZ', 'Algeria');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DS', 'American Samoa');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AD', 'Andorra');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AO', 'Angola');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AI', 'Anguilla');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AQ', 'Antarctica');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AG', 'Antigua and Barbuda');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AR', 'Argentina');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AM', 'Armenia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AW', 'Aruba');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AU', 'Australia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AT', 'Austria');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AZ', 'Azerbaijan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BS', 'Bahamas');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BH', 'Bahrain');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BD', 'Bangladesh');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BB', 'Barbados');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BY', 'Belarus');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BE', 'Belgium');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BZ', 'Belize');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BJ', 'Benin');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BM', 'Bermuda');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BT', 'Bhutan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BO', 'Bolivia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BA', 'Bosnia and Herzegovina');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BW', 'Botswana');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BV', 'Bouvet Island');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BR', 'Brazil');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IO', 'British Indian Ocean Territory');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BN', 'Brunei Darussalam');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BG', 'Bulgaria');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BF', 'Burkina Faso');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'BI', 'Burundi');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KH', 'Cambodia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CM', 'Cameroon');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CA', 'Canada');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CV', 'Cape Verde');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KY', 'Cayman Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CF', 'Central African Republic');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TD', 'Chad');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CL', 'Chile');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CN', 'China');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CX', 'Christmas Island');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CC', 'Cocos (Keeling) Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CO', 'Colombia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KM', 'Comoros');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CG', 'Congo');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CK', 'Cook Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CR', 'Costa Rica');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'HR', 'Croatia (Hrvatska)');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CU', 'Cuba');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CY', 'Cyprus');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CZ', 'Czech Republic');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DK', 'Denmark');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DJ', 'Djibouti');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DM', 'Dominica');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DO', 'Dominican Republic');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TP', 'East Timor');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'EC', 'Ecuador');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'EG', 'Egypt');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SV', 'El Salvador');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GQ', 'Equatorial Guinea');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ER', 'Eritrea');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'EE', 'Estonia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ET', 'Ethiopia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FK', 'Falkland Islands (Malvinas)');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FO', 'Faroe Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FJ', 'Fiji');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FI', 'Finland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FR', 'France');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FX', 'France, Metropolitan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GF', 'French Guiana');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PF', 'French Polynesia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TF', 'French Southern Territories');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GA', 'Gabon');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GM', 'Gambia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GE', 'Georgia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'DE', 'Germany');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GH', 'Ghana');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GI', 'Gibraltar');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GK', 'Guernsey');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GR', 'Greece');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GL', 'Greenland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GD', 'Grenada');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GP', 'Guadeloupe');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GU', 'Guam');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GT', 'Guatemala');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GN', 'Guinea');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GW', 'Guinea-Bissau');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GY', 'Guyana');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'HT', 'Haiti');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'HM', 'Heard and Mc Donald Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'HN', 'Honduras');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'HK', 'Hong Kong');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'HU', 'Hungary');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IS', 'Iceland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IN', 'India');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IM', 'Isle of Man');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ID', 'Indonesia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IR', 'Iran (Islamic Republic of)');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IQ', 'Iraq');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IE', 'Ireland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IL', 'Israel');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'IT', 'Italy');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CI', 'Ivory Coast');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'JE', 'Jersey');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'JM', 'Jamaica');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'JP', 'Japan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'JO', 'Jordan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KZ', 'Kazakhstan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KE', 'Kenya');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KI', 'Kiribati');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KP', 'Korea, Democratic People''s Republic of');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KR', 'Korea, Republic of');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'XK', 'Kosovo');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KW', 'Kuwait');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KG', 'Kyrgyzstan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LA', 'Lao People''s Democratic Republic');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LV', 'Latvia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LB', 'Lebanon');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LS', 'Lesotho');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LR', 'Liberia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LY', 'Libyan Arab Jamahiriya');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LI', 'Liechtenstein');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LT', 'Lithuania');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LU', 'Luxembourg');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MO', 'Macau');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MK', 'Macedonia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MG', 'Madagascar');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MW', 'Malawi');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MY', 'Malaysia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MV', 'Maldives');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ML', 'Mali');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MT', 'Malta');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MH', 'Marshall Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MQ', 'Martinique');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MR', 'Mauritania');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MU', 'Mauritius');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TY', 'Mayotte');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MX', 'Mexico');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'FM', 'Micronesia, Federated States of');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MD', 'Moldova, Republic of');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MC', 'Monaco');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MN', 'Mongolia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ME', 'Montenegro');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MS', 'Montserrat');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MA', 'Morocco');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MZ', 'Mozambique');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MM', 'Myanmar');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NA', 'Namibia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NR', 'Nauru');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NP', 'Nepal');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NL', 'Netherlands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AN', 'Netherlands Antilles');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NC', 'New Caledonia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NZ', 'New Zealand');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NI', 'Nicaragua');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NE', 'Niger');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NG', 'Nigeria');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NU', 'Niue');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NF', 'Norfolk Island');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'MP', 'Northern Mariana Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'NO', 'Norway');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'OM', 'Oman');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PK', 'Pakistan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PW', 'Palau');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PS', 'Palestine');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PA', 'Panama');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PG', 'Papua New Guinea');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PY', 'Paraguay');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PE', 'Peru');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PH', 'Philippines');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PN', 'Pitcairn');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PL', 'Poland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PT', 'Portugal');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PR', 'Puerto Rico');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'QA', 'Qatar');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'RE', 'Reunion');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'RO', 'Romania');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'RU', 'Russian Federation');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'RW', 'Rwanda');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'KN', 'Saint Kitts and Nevis');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LC', 'Saint Lucia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VC', 'Saint Vincent and the Grenadines');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'WS', 'Samoa');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SM', 'San Marino');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ST', 'Sao Tome and Principe');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SA', 'Saudi Arabia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SN', 'Senegal');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'RS', 'Serbia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SC', 'Seychelles');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SL', 'Sierra Leone');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SG', 'Singapore');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SK', 'Slovakia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SI', 'Slovenia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SB', 'Solomon Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SO', 'Somalia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ZA', 'South Africa');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GS', 'South Georgia South Sandwich Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ES', 'Spain');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'LK', 'Sri Lanka');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SH', 'St. Helena');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'PM', 'St. Pierre and Miquelon');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SD', 'Sudan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SR', 'Suriname');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SJ', 'Svalbard and Jan Mayen Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SZ', 'Swaziland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SE', 'Sweden');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'CH', 'Switzerland');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'SY', 'Syrian Arab Republic');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TW', 'Taiwan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TJ', 'Tajikistan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TZ', 'Tanzania, United Republic of');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TH', 'Thailand');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TG', 'Togo');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TK', 'Tokelau');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TO', 'Tonga');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TT', 'Trinidad and Tobago');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TN', 'Tunisia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TR', 'Turkey');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TM', 'Turkmenistan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TC', 'Turks and Caicos Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'TV', 'Tuvalu');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'UG', 'Uganda');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'UA', 'Ukraine');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'AE', 'United Arab Emirates');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'GB', 'United Kingdom');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'US', 'United States');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'UM', 'United States minor outlying islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'UY', 'Uruguay');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'UZ', 'Uzbekistan');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VU', 'Vanuatu');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VA', 'Vatican City State');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VE', 'Venezuela');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VN', 'Vietnam');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VG', 'Virgin Islands (British)');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'VI', 'Virgin Islands (U.S.)');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'WF', 'Wallis and Futuna Islands');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'EH', 'Western Sahara');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'YE', 'Yemen');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ZR', 'Zaire');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ZM', 'Zambia');
INSERT INTO COUNTRY VALUES (nextval('SQ_COUNTRY_PK'), 'ZW', 'Zimbabwe');